name: mobile_mexico
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - img/MÉXICO.jpg
    - img/culinaria.jpg
    - img/cultura.jpg
    - img/geografia.jpg
    - img/lucas.jpg
    - img/guilherme.jpg
    - img/bigode.png
    - img/cacto.png
    - img/caveira.png
    - img/danca.png
    - img/tacos.jpg
    - img/restaurante.jpg
    - img/comidas.png
    - img/mapa.jpg
    - img/clima.jpg
    - img/populacao.jpg
    - img/politica.jpg
    - img/economia.jpg
   